[package]
name = "astroxide"
version = "0.0.5"
edition = "2024"
description = "Astronomy utils for Rust."
license = "MIT"


[dependencies]
libm = "0.2.15"
phf = { version = "0.12.1", features = ["macros"] }
