[package]
name = "astroxide"
version = "0.0.13"
edition = "2024"
description = "Astronomy utils for Rust."
license = "MIT"


[dependencies]
kiddo = "5.2.2"
libm = "0.2.15"
phf = { version = "0.12.1", features = ["macros"] }
rayon = "1.11.0"
